connection <- file("household_power_consumption.txt")
open(connection)
header <- read.table(connection, nrow=1, sep=";", header=TRUE)
power <- read.table(connection, skip=66635, nrow=2880, sep=";")
close(connection)
names(power) <- names(header)

png("plot3.png")
plot(power$Sub_metering_1, type="l", xaxt="n", xlab="", ylab="Energy sub metering")
points(power$Sub_metering_2, type="l", col="red")
points(power$Sub_metering_3, type="l", col="blue")
dataLength <- length(power$Global_active_power)
axis(side=1, at=c(0, dataLength/2, dataLength), labels=c("Thu", "Fri", "Sat"))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=c(1,1))
dev.off()
